always-run:
  script: echo 'this should always run'

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests
    - [branches]

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
    
